# general settings
set -g prefix C-f
unbind C-b
set -g status-position bottom 
set -g mouse on
set -g renumber-windows on
set -g window-status-format "#W"
set -g window-status-current-format "#W"

# split panes
bind | split-window -h
bind - split-window -v

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'o0th/tmux-nova'

# tmux nova
set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 

set -g @nova-pane-active-border-style "#57e389"
set -g @nova-pane-border-style "#383838"
set -g @nova-status-style-bg "#242424"
set -g @nova-status-style-fg "#ffffff"
set -g @nova-status-style-active-bg "#57e389"
set -g @nova-status-style-active-fg "#ffffff"
set -g @nova-status-style-double-bg "#383838"

set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

set -g @nova-segment-mode "#{?client_prefix,,}"
set -g @nova-segment-mode-colors "#383838 #ffffff"

set -g @nova-segment-whoami "#(whoami)"
set -g @nova-segment-whoami-colors "#57e389 #ffffff"

set -g @nova-rows 0
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "whoami"

# continuum
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

run '~/.tmux/plugins/tpm/tpm'
